### ISSUE TITLE
npm vs yarn

### ISSUE THREAD

**Issue by apotdevin** [byteleaf/companyon-frontend#26]
Any reason why we use yarn? Just thinking ahead for a FOSS project might be interesting to use npm over yarn. It's one dependency less that needs to be installed by the users. Also normally any cloud deployment server already has npm installed which makes it easier :)

**Comment by heerma** [comment]
Yeah less dependencies are always better, that's true. We should just make sure we all stick to one, so if you want to change it, please also write it into the readme :)

**Comment by apotdevin** [comment]
Closed by https://github.com/byteleaf/companyon-frontend/pull/30
