### ISSUE TITLE
Need to reauth on each page refresh

### ISSUE THREAD

**Issue by apotdevin** [byteleaf/companyon-frontend#28]
Every time you refresh the page you are redirected and asked to auth again. Happens locally don't know if in prod env.

Would be nice to remove this bug

**Comment by markus-heer** [comment]
Yes totally. We need to save the token we get from Auth0. This can be done via localStorage and via http safe cookies. I would prefer the latter, but we also need to make sure this cookie gets then passed to the backend. This is the most secure kind of storing and transferring a token, so i would definitely try to go for it. @sauterle-byteleaf we talked about this during the last hackathon, can you remember why it was not possible to pass it to the Spring Boot backend via cookies?

**Comment by apotdevin** [comment]
Found this online issue about persisting the authentication with auth0: https://community.auth0.com/t/react-with-auth0-spa-looses-login-after-refresh/35461/8

![image](https://user-images.githubusercontent.com/31413433/104306432-368ae300-54ce-11eb-9720-52c744d3f277.png)

**Comment by apotdevin** [comment]
Fixed. The reason was that the auth client from Auth0 was using dev keys that are unable to persist the account logins. Following the instructions above, I created a google app with a OAuth Client ID and used those keys to connect Auth0.

Login attempts are now persisted 🥳🙌🥳

**Comment by heerma** [comment]
Nice, can you add the steps to the readme? So that we have some kind of FAQ for issues that might pop up for other people.
